# Generated by Django 5.2.6 on 2026-02-16 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_check_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_text', models.TextField(default='')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
                ('about_title', models.CharField(max_length=200)),
                ('about_text', models.TextField(default='')),
                ('vision_title', models.CharField(default='', max_length=200)),
                ('vision_text', models.TextField(default='')),
                ('mission_title', models.CharField(default='', max_length=200)),
                ('mission_text', models.TextField(default='')),
                ('values_title', models.CharField(default='', max_length=200)),
                ('values_text', models.TextField(default='')),
                ('stat1_number', models.CharField(default='10+', max_length=20)),
                ('stat1_text', models.CharField(default='Yıllık Deneyim', max_length=200)),
                ('stat2_number', models.CharField(default='500+', max_length=20)),
                ('stat2_text', models.CharField(default='Global Müşteri', max_length=200)),
                ('stat3_number', models.CharField(default='1200+', max_length=20)),
                ('stat3_text', models.CharField(default='Tamamlanan Proje', max_length=200)),
                ('stat4_number', models.CharField(default='24/7', max_length=20)),
                ('stat4_text', models.CharField(default='Destek Hizmeti', max_length=200)),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200, verbose_name='Başlık (Hero)')),
                ('hero_text', models.TextField(verbose_name='Açıklama (Hero)')),
                ('hero_image', models.ImageField(default='default_blog.jpg', upload_to='blog/', verbose_name='Görsel (Hero)')),
            ],
            options={
                'verbose_name': 'Blog Sayfası',
                'verbose_name_plural': 'Blog Sayfası',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Şirket Adı')),
                ('address', models.CharField(max_length=300, verbose_name='Adres')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': 'Şirket Bilgisi',
                'verbose_name_plural': 'Şirket Bilgisi',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(default='team_hero/default_team_hero.jpg', upload_to='team_hero/')),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('position', models.CharField(max_length=150, verbose_name='Pozisyon')),
                ('bio', models.TextField(verbose_name='Açıklama')),
                ('photo', models.ImageField(upload_to='employees/', verbose_name='Fotoğraf')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Çalışan',
                'verbose_name_plural': 'Çalışanlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200, verbose_name='Başlık (Hero)')),
                ('hero_text', models.TextField(verbose_name='Açıklama (Hero)')),
                ('hero_image', models.ImageField(default='default_services.jpg', upload_to='services/', verbose_name='Görsel (Hero)')),
            ],
            options={
                'verbose_name': 'Hizmet Sayfası',
                'verbose_name_plural': 'Hizmet Sayfası',
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=200, verbose_name='Ana Sayfa Başlığı')),
                ('home_text', models.TextField(verbose_name='Ana Sayfa Metni')),
                ('about_title', models.CharField(max_length=200, verbose_name='Hakkımızda Başlığı')),
                ('about_text', models.TextField(verbose_name='Hakkımızda Metni')),
                ('footer_text', models.TextField(verbose_name='Alt Bilgi (Footer)')),
            ],
            options={
                'verbose_name': 'Site İçeriği',
                'verbose_name_plural': 'Site İçeriği',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(default='default_post.jpg', upload_to='blog/', verbose_name='Görsel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.blogpage', verbose_name='Sayfa')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(default='default_service.jpg', upload_to='services/', verbose_name='Görsel')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='main.servicespage', verbose_name='Sayfa')),
            ],
            options={
                'verbose_name': 'Çalışma Alanı',
                'verbose_name_plural': 'Çalışma Alanı',
                'ordering': ['order'],
            },
        ),
    ]
