# Generated by Django 5.2.6 on 2026-02-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Longitude'),
        ),
    ]
