# Generated by Django 5.2.6 on 2026-02-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_companyinfo_lat_companyinfo_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Pozisyon Başlığı')),
                ('description', models.TextField(verbose_name='Pozisyon Açıklaması')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lokasyon')),
                ('posted_date', models.DateField(auto_now_add=True, verbose_name='Yayın Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'İş İlanı',
                'verbose_name_plural': 'İş İlanları',
                'ordering': ['-posted_date'],
            },
        ),
    ]
