# Generated by Django 5.2.6 on 2026-02-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_karier'),
    ]

    operations = [
        migrations.AddField(
            model_name='karier',
            name='page_image',
            field=models.ImageField(blank=True, null=True, upload_to='kariyer_images/', verbose_name='Sayfa Görseli'),
        ),
        migrations.AddField(
            model_name='karier',
            name='page_title',
            field=models.CharField(default='Kariyer', max_length=250, verbose_name='Sayfa Başlığı'),
        ),
    ]
