# Generated by Django 5.2.6 on 2026-02-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_karier_page_image_karier_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='homepage_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage_images/', verbose_name='Ana Sayfa Resmi'),
        ),
    ]
