# Generated by Django 5.2.6 on 2026-02-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_companyinfo_homepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='comminication_image',
            field=models.ImageField(blank=True, null=True, upload_to='comminication_images/', verbose_name='İletişim Resmi'),
        ),
    ]
