# Generated by Django 5.2.6 on 2026-02-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_companyinfo_comminication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='page_text',
            field=models.TextField(default='Profesyonel ve deneyimli ekibimizle hizmetinizdeyiz.', verbose_name='AEkip Sayfası Metni'),
        ),
        migrations.AddField(
            model_name='employee',
            name='page_title',
            field=models.CharField(default='Ekibimiz', max_length=200, verbose_name='Ekip Sayfası Başlığı'),
        ),
    ]
