# Generated by Django 5.2.6 on 2026-02-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_employee_page_text_employee_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(default='team_hero/default_team_hero.jpg', upload_to='team_hero/')),
                ('title', models.CharField(default='Ekibimiz', max_length=200, verbose_name='Ekip Sayfası Başlığı')),
                ('text', models.TextField(default='Profesyonel ve deneyimli ekibimizle hizmetinizdeyiz.', verbose_name='Ekip Sayfası Metni')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='page_text',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='page_title',
        ),
    ]
