# Generated by Django 6.0.4 on 2026-04-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_teampage_remove_employee_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hero_image',
            field=models.ImageField(default='team_hero/default_team_hero.jpg', upload_to='team_hero/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='page_text',
            field=models.TextField(default='Profesyonel ve deneyimli ekibimizle hizmetinizdeyiz.', verbose_name='AEkip Sayfası Metni'),
        ),
        migrations.AddField(
            model_name='employee',
            name='page_title',
            field=models.CharField(default='Ekibimiz', max_length=200, verbose_name='Ekip Sayfası Başlığı'),
        ),
    ]
