# Generated by Django 6.0.4 on 2026-04-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_employee_hero_image_employee_page_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='page_text',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='page_title',
        ),
    ]
