# Generated by Django 6.0.4 on 2026-04-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_employee_hero_image_employee_page_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamPage',
        ),
    ]
