# Generated by Django 6.0.4 on 2026-04-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_teampage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(default='team_hero/default_team_hero.jpg', upload_to='team_hero/')),
                ('title', models.CharField(default='Ekibimiz', max_length=200, verbose_name='Ekip Sayfası Başlığı')),
                ('text', models.TextField(default='Profesyonel ve deneyimli ekibimizle hizmetinizdeyiz.', verbose_name='Ekip Sayfası Metni')),
            ],
        ),
    ]
