# Generated by Django 6.0.4 on 2026-04-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_teampage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default='default_post.jpg', null=True, upload_to='blog/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık'),
        ),
    ]
