# Generated by Django 6.0.4 on 2026-04-19 06:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_blogpost_image_alter_blogpost_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme'),
        ),
        migrations.AddField(
            model_name='karier',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih'),
        ),
        migrations.AddField(
            model_name='karier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih'),
        ),
    ]
