# Generated by Django 6.0.4 on 2026-04-19 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_aboutpage_updated_at_blogpost_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme'),
        ),
    ]
