# Generated by Django 6.0.4 on 2026-04-19 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_blogpage_created_at_blogpage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme'),
        ),
    ]
